name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2

    - name: Fixup url for submodules
      run: perl -pi -e 's/git\@github.com:/https:\/\/github.com\//' .git/config .gitmodules
  
    - name: Submodule update
      run: git submodule init; git submodule update --recursive

    - name: Checkout esctest for testing
      run: git clone https://github.com/migueldeicaza/esctest.git

    - name: List all files, because this is driving me insane, this does not repro anywhere but github
      run: ls -lR 

    - name: Xcode Mac Build
      #run: swift build -v
      run: xcodebuild -scheme MacTerminal -workspace SwiftTerm.xcworkspace

    - name: Xcode iOS Build
      run: xcodebuild -scheme iOSTerminal -workspace SwiftTerm.xcworkspace -destination "platform=iOS Simulator,id=`instruments -s devices | grep iPhone| grep Simulator | sed -e 's/.*\[//' -e 's/\].*//' | head -1`"

    - name: Swift Package Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Coverage
      run: |
        swift test --enable-code-coverage
        BINDIR=`swift build --show-bin-path`
        TESTDIR=`find $BINDIR -name '*.xctest'`
        xcrun llvm-cov report $TESTDIR/Contents/MacOS/SwiftTermPackageTests --instr-profile=.build/debug/codecov/default.profdata -use-color
